dataset:
  name: run0
  raw_file: /Users/karahanyilmazer/Coding/python/neuro/data/charite-neurofeedback/ID285/day0/qEEG_AntoniaGuzman_openeyes.vhdr
montage:
  montage_file: null
  head_size: null
cropping:
  tmin: 6.0
  tmax: 606.0
filtering:
  highpass: 1.0
  lowpass: 40.0
  notch:
    - 50.0
    - 100.0
channels:
  drop:
    - ecg
    - eda
    - envelope
    - envelope_am
  bads:
    - C6
    - F9
    - Fpz
    - Fp1
    - FT9
    - FT10
    - TP9
    - TP10
  sketchy:
    - T7
    - C3
rereferencing:
  method: average
bad_spans:
  - onset: 94
    duration: 0.5
    description: bad_span
  - onset: 167
    duration: 3
    description: bad_span
  - onset: 197
    duration: 5
    description: bad_span
  - onset: 254
    duration: 1.5
    description: bad_span
  - onset: 431.5
    duration: 7
    description: bad_span
  - onset: 468.5
    duration: 4
    description: bad_span
  - onset: 588
    duration: 8
    description: bad_span
ica:
  n_components: null
  random_state: 1
  method: infomax
  max_iter: auto
  reject_by_annotation: true
  fit_params:
    extended: true
  rejection_thr: 0.9
  exclude_components:
    - 0
    - 1
    - 2
    - 3
    - 5
    - 8
    - 9
    - 11
    - 16 
    - 23
    - 24
    - 25
    - 31
    
output:
  save_dir: results/preprocessed/
  save_format: fif.gz