dataset:
  name: run2
  raw_file: /Users/karahanyilmazer/Coding/python/neuro/data/charite-neurofeedback/ID285/day8/sub-P001_ses-S001_task-rest-eo_run-001_eeg.xdf
cropping:
  tmin: 2
  tmax: 212
filtering:
  highpass: 1.0
  lowpass: 40.0
  notch: null
channels:
  bads:
  - FT9
  - FT10
  - P7
  - P8
  - TP9
  - TP10
  - T7
  - T8
  sketchy:
rereferencing:
  method: average
bad_spans:
  # - onset: 263
  #   duration: 5
  #   description: bad_span
ica:
  n_components: null
  random_state: 1
  method: infomax
  max_iter: auto
  reject_by_annotation: true
  fit_params:
    extended: true
  rejection_thr: 0.7
  exclude_components:
  - 0
  - 1
  - 7
  - 10
output:
  save_dir: results/preprocessed/
  save_format: fif.gz
